version: "3.3"

services:
  frontend:
    deploy:
      replicas: 2
    image: ctapp/frontend:latest
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - backend

  backend:
    deploy:
      replicas: 2
    image: ctapp/backend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - backend

  gateway:
    image: nginx:latest
    deploy:
      replicas: 1
    ports:
      - 80:80
      # - 443:443
    volumes:
      - /tmp/login-app2/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - /tmp/nginx/certs:/data
    networks:
      - backend

networks:
  backend:
